### ISSUE TITLE
Highscore.txt: FileNotFoundError: No such file or directory

### ISSUE THREAD

**Issue by Furbinator** [Aeryes/Demented#6]
I'm trying to get your game working, but the code hits an exception trying to a file to read the contents.
C:\\Users\\Anon\\Desktop\\Demented-master\\highscore.txt

**Comment by Aeryes** [comment]
I know what the issue is. Thank you for bringing it to light. I'll fix the path issues later today.

**Comment by Aeryes** [comment]
Okay can you try and run it now? It should be fixed. Just make sure the contents are all in the one folder.
